--
-- Author: pengxianfeng
-- Date: 2017-04-26 14:08:33
--
-- type 0 texture png file
-- type 1 texture with plist file
-- type 2 spine, 不指定scale,getSpine()时指定scale,与元素有关放在ElementsResource
-- type 3 sfx 音乐音效资源,与元素有关放在ElementsResource
-- 'load' 为进入该场景预加载的资源,默认load中的数据如果不在keep中则离开该场景时卸载
-- 'extraUnload' 为离开该场景指定卸载的资源
-- 'keep' 为离开该场景不卸载的资源

local resources = {
    ['app.StartAndUpdateScene'] = {
        ['loadRGBA8888']={
            {0, 'startBg.jpg'},
        },
         ['load'] = {
             {0, 'gfx/start/l_btn.png'},
             {0, 'gfx/start/startsBtn.png'},

             {0, 'gfx/start/fb_login_tips.png'},
             {0, 'gfx/start/start_progress_bar.png'},
             {0, 'gfx/start/start_progress_bg.png'},
             {0, 'gfx/start/start_progress_mask.png'},
             {0, 'gfx/start/update_skip.png'},
             {1, 'common.plist', 'common.pvr'},
             {1, 'tower_common.plist', 'tower_common.pvr'},
             {1, 'avatar.plist', 'avatar.pvr'},
             {3,"ui_leveltransition_close"},
             {3,"ui_leveltransition_open"},
         },
         ['extraUnload'] = {
             {0, 'startBg.jpg'},
             {0,'toonsTv.png'},
         },
         ['keep'] = {
             {1, 'common.plist', 'common.pvr'},
             {1, 'tower_common.plist', 'tower_common.pvr'},
             {1, 'avatar.plist', 'avatar.pvr'},
             {3,"ui_leveltransition_close"},
             {3,"ui_leveltransition_open"},
         },
    },

    ['app.towerscene.PigTowerScene'] = {
        ['loadRGBA8888']={
            -- {0,"GalleryBg.png"},
            {2,"effect/pigtower/gallerylight.json" ,"effect/pigtower/gallerylight.atlas" ,"effect/pigtower/gallerylight.png"},
        },
        ['load'] = {
            {1,"gallery.plist","gallery.pvr"},
            {1, 'map_ui.plist', 'map_ui.pvr'},
            {1, 'graybtn.plist', 'graybtn.pvr'},
            {1, 'tower_ui.plist', 'tower_ui.pvr'},
            {1,"level.plist","level.pvr"},
            {2,"effect/pigtower/ripple.json" ,"effect/pigtower/ripple.atlas" ,"effect/pigtower/ripple.png"},
            {2,"effect/pigtower/tree.json" ,"effect/pigtower/tree.atlas" ,"effect/pigtower/tree.png"},
        },
        ['extraUnload'] = {
            {0,"GalleryBg.png"},
            -- {2,"effect/pigtower/pigtower.json" ,"effect/pigtower/pigtower.atlas" ,"effect/pigtower/pigtower.png"},
            -- {2,"effect/pigtower/leaf.json" ,"effect/pigtower/leaf.atlas" ,"effect/pigtower/leaf.png"},
        },
        ['keep'] = {

        },
    },

    ['app.mapscene.MapScene'] = {
        ['loadRGBA8888']={
              {1, 'graybtn.plist', 'graybtn.pvr'},
              {2, "effect/mapLock/mapcloud.json","effect/mapLock/mapcloud.atlas","effect/mapLock/mapcloud.png"},
              {2, "effect/rank_up/trophy.json", "effect/rank_up/trophy.atlas", "effect/rank_up/trophy.png"},
        },
         ['load'] = {
             {0,"piggy_first.png"},
             {1, 'map_ui.plist', 'map_ui.pvr'},
             {1, 'shop.plist', 'shop.pvr'},
             -- map hatchling动画
             {2, "effect/hatchling/pink.json", "effect/hatchling/pink.atlas", "effect/hatchling/pink.png"},
             {2, "effect/hatchling/white.json", "effect/hatchling/white.atlas", "effect/hatchling/white.png"},
             {2, "effect/hatchling/blue.json", "effect/hatchling/blue.atlas", "effect/hatchling/blue.png"},
             {2, "effect/hatchling/green.json", "effect/hatchling/green.atlas", "effect/hatchling/green.png"},
             {2, "effect/hatchling/purple.json", "effect/hatchling/purple.atlas", "effect/hatchling/purple.png"},
             {2, "effect/hatchling/brown.json", "effect/hatchling/brown.atlas", "effect/hatchling/brown.png"},
             {2, "effect/hatchling/red.json", "effect/hatchling/red.atlas", "effect/hatchling/red.png"},
             {2, "effect/hatchling/effect.json", "effect/hatchling/effect.atlas", "effect/hatchling/effect.png"},
             --  level_mark
             {2, "effect/level_mark/skeleton_red.json", "effect/level_mark/skeleton_red.atlas", "effect/level_mark/skeleton_red.png"},
             -- 通用音效
             {3,"ui_show_panel"},
             {3,"ui_close_panel"},
             {3,"ui_show_target"},
             {3,"ui_hide_target"},
             {3,"ui_exit"},
             {3,"ui_buy"},
             {3,"common_click"},
             {3,"common_menu"},
             {3,"refueling_bird"},
             -- 非通用音效
             {3,"ui_nextlevel_unlocked"},
             {3,"gold_fly"},
             {3,"silver_fly"},
             {3,"select_level_bird_jump"},
             {3,"hp_full_animation"},
         },
         ['extraUnload'] = {
             {0,"piggy_first.png"},
             {1, 'graybtn.plist', 'graybtn.pvr'},
             {0,"bg/battle_continue_bg_01.png"},
             {0,"bg/battle_continue_bg_02.png"},
             {0,"bg/battle_continue_bg_03.png"},
             {0,"bg/battle_continue_bg_04.png"},
             {0,"bg/begin_01.png"},
             {0,"bg/begin_02.png"},
             {0,"bg/begin_03.png"},
             {0,"bg/begin_04.png"},
             {0,"bg/dailyImg_01.png"},
             {0,"bg/dailyImg_02.png"},
             {0,"bg/dailyImg_03.png"},
             {0,"bg/dailyImg_04.png"},
             {0,"bg/frame_max_01.png"},
             {0,"bg/frame_max_02.png"},
             {0,"bg/frame_max_03_01.png"},
             {0,"bg/frame_max_03_02.png"},
             {0,"bg/frame_max_03_03.png"},
             {0,"bg/frame_max_03_04.png"},
             {0,"bg/frame_max_03.png"},
             {0,"bg/frame_max_04.png"},
             {0,"bg/frame_median_01.png"},
             {0,"bg/frame_median_02.png"},
             {0,"bg/frame_median_03.png"},
             {0,"bg/frame_median_04.png"},
             {0,"bg/heart_purchase_bg_01.png"},
             {0,"bg/heart_purchase_bg_02.png"},
             {0,"bg/heart_purchase_bg_03.png"},
             {0,"bg/heart_purchase_bg_04.png"},
             {0,"bg/newBg_large_01.png"},
             {0,"bg/newBg_large_02.png"},
             {0,"bg/newBg_large_03.png"},
             {0,"bg/newBg_large_04.png"},
             {0,"bg/newBg_normal_01.png"},
             {0,"bg/newBg_normal_02.png"},
             {0,"bg/newBg_normal_03.png"},
             {0,"bg/newBg_normal_04.png"},
            {0, 'back3.png'},
            {0, 'back4.png'},
            {0, 'circle_mask.png'},
            {0, 'guide_1.png'},
            {0, 'guide_3.png'},
            {0, 'guide_4.png'},
            {0, 'target_mask.png'},
            {0, 'guide_tip_bomb.png'},
            {0, 'guide_tip_gun.png'},
            {0, 'guide_tip_rocket.png'},
            {1, 'daily_task.plist', 'daily_task.pvr'},
            {1, 'message.plist', 'message.pvr'},
            {1, 'mission.plist', 'mission.pvr'},
            {1, 'journey.plist', 'journey.pvr'},
            {1, 'unlock.plist', 'unlock.pvr'},
            {1, 'FriendsBox.plist', 'FriendsBox.pvr'},

            {2, "effect/box_map/skeleton.json", "effect/box_map/skeleton.atlas", "effect/box_map/skeleton.png"},

            {2,"effect/hand/light.json" ,"effect/hand/light.atlas" ,"effect/hand/light.png"},

            {2,"effect/map/ch1/rgba4444/fog.json" ,"effect/map/ch1/rgba4444/fog.atlas" ,"effect/map/ch1/rgba4444/fog.png"},
            {2,"effect/map/ch1/rgba4444/island_water.json" ,"effect/map/ch1/rgba4444/island_water.atlas" ,"effect/map/ch1/rgba4444/island_water.png"},
            {2,"effect/map/ch1/rgba4444/water.json" ,"effect/map/ch1/rgba4444/water.atlas" ,"effect/map/ch1/rgba4444/water.png"},
            {2,"effect/map/ch1/rgba4444/island.json" ,"effect/map/ch1/rgba4444/island.atlas" ,"effect/map/ch1/rgba4444/island.png"},
            {2,"effect/map/ch1/rgba4444/sealianyi.json" ,"effect/map/ch1/rgba4444/sealianyi.atlas" ,"effect/map/ch1/rgba4444/sealianyi.png"},
            {2,"effect/map/ch1/rgba4444/sealianyi2.json" ,"effect/map/ch1/rgba4444/sealianyi2.atlas" ,"effect/map/ch1/rgba4444/sealianyi2.png"},
            {2,"effect/map/ch1/rgba4444/small_island1.json" ,"effect/map/ch1/rgba4444/small_island1.atlas" ,"effect/map/ch1/rgba4444/small_island1.png"},
            {2,"effect/map/ch1/rgba4444/small_island2.json" ,"effect/map/ch1/rgba4444/small_island2.atlas" ,"effect/map/ch1/rgba4444/small_island2.png"},
            {2,"effect/map/ch1/rgba4444/small_island3.json" ,"effect/map/ch1/rgba4444/small_island3.atlas" ,"effect/map/ch1/rgba4444/small_island3.png"},
            {2,"effect/map/ch1/rgba4444/peng.json" ,"effect/map/ch1/rgba4444/peng.atlas" ,"effect/map/ch1/rgba4444/peng.png"},
            {2,"effect/map/ch1/rgba4444/black.json" ,"effect/map/ch1/rgba4444/black.atlas" ,"effect/map/ch1/rgba4444/black.png"},
            {2,"effect/map/ch1/rgba4444/yellow.json" ,"effect/map/ch1/rgba4444/yellow.atlas" ,"effect/map/ch1/rgba4444/yellow.png"},
            {2,"effect/map/ch1/rgba4444/skeleton_blue.json" ,"effect/map/ch1/rgba4444/skeleton_blue.atlas" ,"effect/map/ch1/rgba4444/skeleton_blue.png"},
            {2,"effect/map/ch1/rgba4444/skeleton_white.json" ,"effect/map/ch1/rgba4444/skeleton_white.atlas" ,"effect/map/ch1/rgba4444/skeleton_white.png"},
            {2,"effect/map/ch1/rgba4444/fish.json" ,"effect/map/ch1/rgba4444/fish.atlas" ,"effect/map/ch1/rgba4444/fish.png"},
            {2,"effect/map/ch1/rgba4444/grass_pig.json" ,"effect/map/ch1/rgba4444/grass_pig.atlas" ,"effect/map/ch1/rgba4444/grass_pig.png"},
            {2,"effect/map/common/rgba4444/flag.json" ,"effect/map/common/rgba4444/flag.atlas" ,"effect/map/common/rgba4444/flag.png"},
            {2,"effect/map/common/rgba4444/map_balloon.json" ,"effect/map/common/rgba4444/map_balloon.atlas" ,"effect/map/common/rgba4444/map_balloon.png"},
            {2,"effect/map/common/rgba8888/down.json" ,"effect/map/common/rgba8888/down.atlas" ,"effect/map/common/rgba8888/down.png"},
            {2,"effect/map/ch1/rgba4444/treelight.json" ,"effect/map/ch1/rgba4444/treelight.atlas" ,"effect/map/ch1/rgba4444/treelight.png"},
            {2,"effect/map/ch1/rgba4444/orangeswing.json" ,"effect/map/ch1/rgba4444/orangeswing.atlas" ,"effect/map/ch1/rgba4444/orangeswing.png"},
            {2,"effect/map/ch1/rgba4444/telescope_pig.json" ,"effect/map/ch1/rgba4444/telescope_pig.atlas" ,"effect/map/ch1/rgba4444/telescope_pig.png"},


            {2,"effect/map/unRemove/rgba4444/pigship.json" ,"effect/map/unRemove/rgba4444/pigship.atlas" ,"effect/map/unRemove/rgba4444/pigship.png"},
            {2,"effect/map/unRemove/rgba4444/skeleton.json" ,"effect/map/unRemove/rgba4444/skeleton.atlas" ,"effect/map/unRemove/rgba4444/skeleton.png"},
            {2,"effect/map/unRemove/rgba4444/pigship_straw.json" ,"effect/map/unRemove/rgba4444/pigship_straw.atlas" ,"effect/map/unRemove/rgba4444/pigship_straw.png"},

            {2,"effect/map/ch2/rgba4444/beach_ripple.json" ,"effect/map/ch2/rgba4444/beach_ripple.atlas" ,"effect/map/ch2/rgba4444/beach_ripple.png"},
            {2,"effect/map/ch2/rgba4444/boat.json" ,"effect/map/ch2/rgba4444/boat.atlas" ,"effect/map/ch2/rgba4444/boat.png"},
            {2,"effect/map/ch2/rgba4444/sea_ripple.json" ,"effect/map/ch2/rgba4444/sea_ripple.atlas" ,"effect/map/ch2/rgba4444/sea_ripple.png"},
            {2,"effect/map/ch2/rgba4444/skeleton.json" ,"effect/map/ch2/rgba4444/skeleton.atlas" ,"effect/map/ch2/rgba4444/skeleton.png"},
            {2,"effect/map/common/rgba4444/fishingpig.json" ,"effect/map/common/rgba4444/fishingpig.atlas" ,"effect/map/common/rgba4444/fishingpig.png"},
            {2,"effect/map/ch2/rgba4444/wpig.json" ,"effect/map/ch2/rgba4444/wpig.atlas" ,"effect/map/ch2/rgba4444/wpig.png"},
            {2,"effect/map/ch2/rgba4444/soldier.json" ,"effect/map/ch2/rgba4444/soldier.atlas" ,"effect/map/ch2/rgba4444/soldier.png"},
            {2,"effect/map/ch2/rgba4444/spig.json" ,"effect/map/ch2/rgba4444/spig.atlas" ,"effect/map/ch2/rgba4444/spig.png"},
            {2,"effect/map/ch2/rgba4444/shark.json" ,"effect/map/ch2/rgba4444/shark.atlas" ,"effect/map/ch2/rgba4444/shark.png"},
            {2,"effect/map/ch2/rgba4444/pig.json" ,"effect/map/ch2/rgba4444/pig.atlas" ,"effect/map/ch2/rgba4444/pig.png"},
            {2,"effect/map/ch2/rgba4444/coconut.json" ,"effect/map/ch2/rgba4444/coconut.atlas" ,"effect/map/ch2/rgba4444/coconut.png"},

            {2,"effect/map/ch3/rgba4444/island_water.json" ,"effect/map/ch3/rgba4444/island_water.atlas" ,"effect/map/ch3/rgba4444/island_water.png"},
            {2,"effect/map/ch3/rgba4444/desertmap_pig.json" ,"effect/map/ch3/rgba4444/desertmap_pig.atlas" ,"effect/map/ch3/rgba4444/desertmap_pig.png"},
            {2,"effect/map/ch3/rgba4444/desertmap_sign.json" ,"effect/map/ch3/rgba4444/desertmap_sign.atlas" ,"effect/map/ch3/rgba4444/desertmap_sign.png"},

            {2,"effect/map/ch4/rgba4444/greencirrus.json" ,"effect/map/ch4/rgba4444/greencirrus.atlas" ,"effect/map/ch4/rgba4444/greencirrus.png"},
            {2,"effect/map/ch4/rgba4444/torch.json" ,"effect/map/ch4/rgba4444/torch.atlas" ,"effect/map/ch4/rgba4444/torch.png"},
            {2,"effect/map/ch4/rgba4444/pot.json" ,"effect/map/ch4/rgba4444/pot.atlas" ,"effect/map/ch4/rgba4444/pot.png"},
            {2,"effect/map/ch4/rgba4444/pot_pig.json" ,"effect/map/ch4/rgba4444/pot_pig.atlas" ,"effect/map/ch4/rgba4444/pot_pig.png"},
            {2,"effect/map/ch4/rgba4444/skeleton.json" ,"effect/map/ch4/rgba4444/skeleton.atlas" ,"effect/map/ch4/rgba4444/skeleton.png"},
            {2,"effect/map/ch4/rgba4444/mushroom_pig.json" ,"effect/map/ch4/rgba4444/mushroom_pig.atlas" ,"effect/map/ch4/rgba4444/mushroom_pig.png"},
            {2,"effect/map/ch4/rgba4444/stop.json" ,"effect/map/ch4/rgba4444/stop.atlas" ,"effect/map/ch4/rgba4444/stop.png"},
            {2,"effect/map/ch4/rgba4444/eaterflower.json" ,"effect/map/ch4/rgba4444/eaterflower.atlas" ,"effect/map/ch4/rgba4444/eaterflower.png"},
            {2,"effect/map/ch4/rgba4444/tree.json" ,"effect/map/ch4/rgba4444/tree.atlas" ,"effect/map/ch4/rgba4444/tree.png"},
            {2,"effect/map/common/rgba4444/bulb.json" ,"effect/map/common/rgba4444/bulb.atlas" ,"effect/map/common/rgba4444/bulb.png"},
            {2,"effect/map/ch4/rgba4444/pig.json" ,"effect/map/ch4/rgba4444/pig.atlas" ,"effect/map/ch4/rgba4444/pig.png"},

            {2,"effect/map/ch5/rgba4444/fire.json" ,"effect/map/ch5/rgba4444/fire.atlas" ,"effect/map/ch5/rgba4444/fire.png"},
            {2,"effect/map/ch5/rgba4444/KF.json" ,"effect/map/ch5/rgba4444/KF.atlas" ,"effect/map/ch5/rgba4444/KF.png"},
            {2,"effect/map/ch5/rgba4444/pigcitymap_sign.json" ,"effect/map/ch5/rgba4444/pigcitymap_sign.atlas" ,"effect/map/ch5/rgba4444/pigcitymap_sign.png"},
            {2,"effect/map/ch5/rgba4444/moat.json" ,"effect/map/ch5/rgba4444/moat.atlas" ,"effect/map/ch5/rgba4444/moat.png"},
            {2,"effect/map/ch5/rgba4444/gatewatchpig.json" ,"effect/map/ch5/rgba4444/gatewatchpig.atlas" ,"effect/map/ch5/rgba4444/gatewatchpig.png"},
            {2,"effect/map/ch5/rgba4444/hornpig.json" ,"effect/map/ch5/rgba4444/hornpig.atlas" ,"effect/map/ch5/rgba4444/hornpig.png"},
            {2,"effect/map/ch5/rgba4444/pig.json" ,"effect/map/ch5/rgba4444/pig.atlas" ,"effect/map/ch5/rgba4444/pig.png"},
            {2,"effect/map/ch5/rgba4444/richman.json" ,"effect/map/ch5/rgba4444/richman.atlas" ,"effect/map/ch5/rgba4444/richman.png"},
            {2,"effect/map/ch5/rgba4444/knight.json" ,"effect/map/ch5/rgba4444/knight.atlas" ,"effect/map/ch5/rgba4444/knight.png"},
            {2,"effect/map/ch5/rgba4444/cart_pig.json" ,"effect/map/ch5/rgba4444/cart_pig.atlas" ,"effect/map/ch5/rgba4444/cart_pig.png"},
            {2,"effect/map/ch5/rgba4444/guy.json" ,"effect/map/ch5/rgba4444/guy.atlas" ,"effect/map/ch5/rgba4444/guy.png"},
            {2,"effect/map/ch5/rgba4444/lady.json" ,"effect/map/ch5/rgba4444/lady.atlas" ,"effect/map/ch5/rgba4444/lady.png"},
            {2,"effect/map/ch5/rgba4444/gardener.json" ,"effect/map/ch5/rgba4444/gardener.atlas" ,"effect/map/ch5/rgba4444/gardener.png"},
            {2,"effect/map/ch6/rgba4444/gardenmap_fountain.json" ,"effect/map/ch6/rgba4444/gardenmap_fountain.atlas" ,"effect/map/ch6/rgba4444/gardenmap_fountain.png"},

            {2,"effect/map/ch6/rgba4444/swing_pig.json" ,"effect/map/ch6/rgba4444/swing_pig.atlas" ,"effect/map/ch6/rgba4444/swing_pig.png"},
            {2,"effect/map/ch6/rgba4444/flag_corridor.json" ,"effect/map/ch6/rgba4444/flag_corridor.atlas" ,"effect/map/ch6/rgba4444/flag_corridor.png"},
            {2,"effect/map/ch6/rgba4444/garden_moat.json" ,"effect/map/ch6/rgba4444/garden_moat.atlas" ,"effect/map/ch6/rgba4444/garden_moat.png"},
            {2,"effect/map/ch6/rgba4444/butterfly2.json" ,"effect/map/ch6/rgba4444/butterfly2.atlas" ,"effect/map/ch6/rgba4444/butterfly2.png"},
            {2,"effect/map/ch6/rgba4444/map_balloon.json" ,"effect/map/ch6/rgba4444/map_balloon.atlas" ,"effect/map/ch6/rgba4444/map_balloon.png"},
            {2,"effect/map/ch6/rgba4444/oldwaiter_pig.json" ,"effect/map/ch6/rgba4444/oldwaiter_pig.atlas" ,"effect/map/ch6/rgba4444/oldwaiter_pig.png"},
            {2,"effect/map/ch6/rgba4444/youngwaiter_pig.json" ,"effect/map/ch6/rgba4444/youngwaiter_pig.atlas" ,"effect/map/ch6/rgba4444/youngwaiter_pig.png"},
            {2,"effect/map/ch6/rgba4444/flag.json" ,"effect/map/ch6/rgba4444/flag.atlas" ,"effect/map/ch6/rgba4444/flag.png"},
            {2,"effect/map/ch6/rgba4444/door.json" ,"effect/map/ch6/rgba4444/door.atlas" ,"effect/map/ch6/rgba4444/door.png"},
            {2,"effect/map/ch6/rgba4444/tree.json" ,"effect/map/ch6/rgba4444/tree.atlas" ,"effect/map/ch6/rgba4444/tree.png"},
            {2,"effect/map/ch6/rgba4444/musican_pig.json" ,"effect/map/ch6/rgba4444/musican_pig.atlas" ,"effect/map/ch6/rgba4444/musican_pig.png"},

            -- item buy bg
            {2, "effect/itembg_light/skeleton.json","effect/itembg_light/skeleton.atlas","effect/itembg_light/skeleton.png"},
            -- skull
            {2, "effect/skull/skull.json","effect/skull/skull.atlas","effect/skull/skull.png"},
            {2, "effect/skull/line.json","effect/skull/line.atlas","effect/skull/line.png"},
            -- level_mark
            {2, "effect/level_mark/circle.json","effect/level_mark/circle.atlas","effect/level_mark/circle.png"},
            {2, "effect/level_mark/skeleton_red.json","effect/level_mark/skeleton_red.atlas","effect/level_mark/skeleton_red.png"},
            {2, "effect/level_mark/star.json","effect/level_mark/star.atlas","effect/level_mark/star.png"},
            -- inflactor
            {2, "effect/inflactor/skeleton.json", "effect/inflactor/skeleton.atlas", "effect/inflactor/skeleton.png"},
            -- line
            {2, "effect/hand/line.json","effect/hand/line.atlas","effect/hand/line.png"},

            {2,"effect/map/ch7/rgba4444/bubble_pig.json" ,"effect/map/ch7/rgba4444/bubble_pig.atlas" ,"effect/map/ch7/rgba4444/bubble_pig.png"},
            {2,"effect/map/ch7/rgba4444/bubble.json" ,"effect/map/ch7/rgba4444/bubble.atlas" ,"effect/map/ch7/rgba4444/bubble.png"},
            {2,"effect/map/ch7/rgba8888/aurora.json","effect/map/ch7/rgba8888/aurora.atlas","effect/map/ch7/rgba8888/aurora.png"},
            {2,"effect/map/ch7/rgba4444/car_repair.json","effect/map/ch7/rgba4444/car_repair.atlas","effect/map/ch7/rgba4444/car_repair.png"},
            {2,"effect/map/ch7/rgba4444/snowman.json" ,"effect/map/ch7/rgba4444/snowman.atlas","effect/map/ch7/rgba4444/snowman.png"},
            {2,"effect/map/ch7/rgba4444/snowballpig.json" ,"effect/map/ch7/rgba4444/snowballpig.atlas","effect/map/ch7/rgba4444/snowballpig.png"},
            {2,"effect/map/common/rgba4444/fishingpig.json","effect/map/common/rgba4444/fishingpig.atlas","effect/map/common/rgba4444/fishingpig.png"},
            {2,"effect/map/ch7/rgba4444/icemap_sign.json","effect/map/ch7/rgba4444/icemap_sign.atlas","effect/map/ch7/rgba4444/icemap_sign.png"},
            {2,"effect/map/ch7/rgba4444/skeleton.json","effect/map/ch7/rgba4444/skeleton.atlas","effect/map/ch7/rgba4444/skeleton.png"},
            {2,"effect/map/ch7/rgba4444/ice_ripple.json","effect/map/ch7/rgba4444/ice_ripple.atlas","effect/map/ch7/rgba4444/ice_ripple.png"},
            {2,"effect/map/ch7/rgba4444/waterfall.json","effect/map/ch7/rgba4444/waterfall.atlas","effect/map/ch7/rgba4444/waterfall.png"},
            {2,"effect/map/ch7/rgba4444/cart_snowpig.json","effect/map/ch7/rgba4444/cart_snowpig.atlas","effect/map/ch7/rgba4444/cart_snowpig.png"},
            {2,"effect/map/ch7/rgba4444/slide_pig.json","effect/map/ch7/rgba4444/slide_pig.atlas","effect/map/ch7/rgba4444/slide_pig.png"},
            {2,"effect/map/ch7/rgba4444/slide_pig_fg.json","effect/map/ch7/rgba4444/slide_pig_fg.atlas","effect/map/ch7/rgba4444/slide_pig_fg.png"},
            {2,"effect/map/ch7/rgba4444/skiingpig.json","effect/map/ch7/rgba4444/skiingpig.atlas","effect/map/ch7/rgba4444/skiingpig.png"},
            {2,"effect/map/ch7/rgba4444/wind.json","effect/map/ch7/rgba4444/wind.atlas","effect/map/ch7/rgba4444/wind.png"},
            {2,"effect/map/ch7/rgba4444/treepig2.json","effect/map/ch7/rgba4444/treepig2.atlas","effect/map/ch7/rgba4444/treepig2.png"},
            {2,"effect/map/ch7/rgba4444/shine.json" ,"effect/map/ch7/rgba4444/shine.atlas","effect/map/ch7/rgba4444/shine.png"},
            {2,"effect/map/ch7/rgba4444/bulb.json" ,"effect/map/ch7/rgba4444/bulb.atlas","effect/map/ch7/rgba4444/bulb.png"},

            {2,"effect/map/ch8/rgba4444/skeleton_UFO.json" ,"effect/map/ch8/rgba4444/skeleton_UFO.atlas","effect/map/ch8/rgba4444/skeleton_UFO.png"},
            {2,"effect/map/ch8/rgba4444/meteor.json" ,"effect/map/ch8/rgba4444/meteor.atlas","effect/map/ch8/rgba4444/meteor.png"},
            {2,"effect/map/ch8/rgba4444/star.json" ,"effect/map/ch8/rgba4444/star.atlas","effect/map/ch8/rgba4444/star.png"},


            {0,"forest_01.pvr.ccz"},
            {0,"forest_01.pvr.ccz"},
            {0,"forest_02.pvr.ccz"},
            {0,"forest_03.pvr.ccz"},
            {0,"forest_04.pvr.ccz"},
            {0,"forest_05.pvr.ccz"},
            {0,"forest_06.pvr.ccz"},
            {0,"forest_07.pvr.ccz"},
            {0,"forest_08.pvr.ccz"},
            {0,"forest_09.pvr.ccz"},
            {0,"forest_10.pvr.ccz"},
            {0,"forest_11.pvr.ccz"},
            {0,"forest_12.pvr.ccz"},
            {0,"forest_13.pvr.ccz"},
            {0,"forest_14.pvr.ccz"},
            {0,"forest_15.pvr.ccz"},
            {0,"forest_16.pvr.ccz"},
            {0,"forest_17.pvr.ccz"},
            {0,"forest_18.pvr.ccz"},
            {0,"forest_19.pvr.ccz"},
            {0,"forest_20.pvr.ccz"},
            {0,"forest_21.pvr.ccz"},
            {0,"forest_22.pvr.ccz"},
            {0,"forest_23.pvr.ccz"},
            {0,"forest_24.pvr.ccz"},
            {0,"forest_25.pvr.ccz"},
            {0,"forest_26.pvr.ccz"},
            {0,"forest_27.pvr.ccz"},
            {0,"forest_28.pvr.ccz"},
            {0,"forest_29.pvr.ccz"},

            {0,'sandyBeach_01.pvr.ccz'},
            {0,'sandyBeach_02.pvr.ccz'},
            {0,'sandyBeach_03.pvr.ccz'},
            {0,'sandyBeach_04.pvr.ccz'},
            {0,'sandyBeach_05.pvr.ccz'},
            {0,'sandyBeach_06.pvr.ccz'},
            {0,'sandyBeach_07.pvr.ccz'},
            {0,'sandyBeach_08.pvr.ccz'},
            {0,'sandyBeach_09.pvr.ccz'},
            {0,'sandyBeach_10.pvr.ccz'},
            {0,'sandyBeach_11.pvr.ccz'},
            {0,'sandyBeach_12.pvr.ccz'},
            {0,'sandyBeach_13.pvr.ccz'},
            {0,'sandyBeach_14.pvr.ccz'},
            {0,'sandyBeach_15.pvr.ccz'},
            {0,'sandyBeach_16.pvr.ccz'},
            {0,'sandyBeach_17.pvr.ccz'},
            {0,'sandyBeach_18.pvr.ccz'},
            {0,'sandyBeach_19.pvr.ccz'},
            {0,'sandyBeach_20.pvr.ccz'},
            {0,'sandyBeach_21.pvr.ccz'},
            {0,'sandyBeach_22.pvr.ccz'},

            {0,'ch1_01.pvr.ccz'},
            {0,'ch1_02.pvr.ccz'},
            {0,'ch1_03.pvr.ccz'},
            {0,'ch1_04.pvr.ccz'},
            {0,'ch1_05.pvr.ccz'},
            {0,'ch1_06.pvr.ccz'},
            {0,'ch1_07.pvr.ccz'},
            {0,'ch1_08.pvr.ccz'},
            {0,'ch1_09.pvr.ccz'},
            {0,'ch1_10.pvr.ccz'},
            {0,'ch1_11.pvr.ccz'},
            {0,'ch1_12.pvr.ccz'},
            {0,'ch1_13.pvr.ccz'},
            {0,'ch1_14.pvr.ccz'},
            {0,'ch1_15.pvr.ccz'},
            {0,'ch1_16.pvr.ccz'},
            {0,'ch1_17.pvr.ccz'},
            {0,'ch1_18.pvr.ccz'},
            {0,'diaoxiang.pvr.ccz'},


            {0,'sea_01.pvr.ccz'},
            {0,'sea_02.pvr.ccz'},
            {0,'sea_03.pvr.ccz'},
            {0,'sea_04.pvr.ccz'},
            {0,'sea_05.pvr.ccz'},
            {0,'sea_06.pvr.ccz'},
            {0,'sea_07.pvr.ccz'},
            {0,'sea_08.pvr.ccz'},
            {0,'sea_09.pvr.ccz'},
            {0,'sea_10.pvr.ccz'},
            {0,'sea_11.pvr.ccz'},
            {0,'sea_12.pvr.ccz'},
            {0,'sea_13.pvr.ccz'},
            {0,'sea_14.pvr.ccz'},
            {0,'sea_15.pvr.ccz'},
            {0,'sea_16.pvr.ccz'},
            {0,'sea_17.pvr.ccz'},
            {0,'sea_18.pvr.ccz'},
            {0,'sea_19.pvr.ccz'},
            {0,'sea_20.pvr.ccz'},
            {0,'sea_21.pvr.ccz'},
            {0,'sea_22.pvr.ccz'},
            {0,'sea_23.pvr.ccz'},

            {0,'map3ori_01.pvr.ccz'},
            {0,'map3ori_02.pvr.ccz'},
            {0,'map3ori_03.pvr.ccz'},
            {0,'map3ori_04.pvr.ccz'},
            {0,'map3ori_05.pvr.ccz'},
            {0,'map3ori_06.pvr.ccz'},
            {0,'map3ori_07.pvr.ccz'},
            {0,'map3ori_08.pvr.ccz'},
            {0,'map3ori_09.pvr.ccz'},
            {0,'map3ori_10.pvr.ccz'},
            {0,'map3ori_11.pvr.ccz'},
            {0,'map3ori_12.pvr.ccz'},
            {0,'map3ori_13.pvr.ccz'},
            {0,'map3ori_14.pvr.ccz'},
            {0,'map3ori_15.pvr.ccz'},
            {0,'map3ori_16.pvr.ccz'},
            {0,'map3ori_17.pvr.ccz'},
            {0,'map3ori_18.pvr.ccz'},
            {0,'map3ori_19.pvr.ccz'},
            {0,'map3ori_20.pvr.ccz'},
            {0,'map3ori_21.pvr.ccz'},
            {0,'map3ori_22.pvr.ccz'},
            {0,'map3ori_23.pvr.ccz'},
            {0,'map3ori_24.pvr.ccz'},
            {0,'map3ori_25.pvr.ccz'},
            {0,'map3ori_26.pvr.ccz'},

            {0,'oasis_01.pvr.ccz'},
            {0,'oasis_02.pvr.ccz'},
            {0,'oasis_03.pvr.ccz'},
            {0,'oasis_04.pvr.ccz'},
            {0,'oasis_05.pvr.ccz'},
            {0,'oasis_06.pvr.ccz'},
            {0,'oasis_07.pvr.ccz'},
            {0,'oasis_08.pvr.ccz'},
            {0,'oasis_09.pvr.ccz'},
            {0,'oasis_10.pvr.ccz'},
            {0,'oasis_11.pvr.ccz'},
            {0,'oasis_12.pvr.ccz'},
            {0,'oasis_13.pvr.ccz'},
            {0,'oasis_14.pvr.ccz'},
            {0,'oasis_15.pvr.ccz'},
            {0,'oasis_16.pvr.ccz'},
            {0,'oasis_17.pvr.ccz'},
            {0,'oasis_18.pvr.ccz'},
            {0,'oasis_19.pvr.ccz'},
            {0,'oasis_20.pvr.ccz'},
            {0,'oasis_21.pvr.ccz'},
            {0,'oasis_22.pvr.ccz'},
            {0,'oasis_23.pvr.ccz'},
            {0,'oasis_24.pvr.ccz'},
            {0,'oasis_25.pvr.ccz'},
            {0,'oasis_26.pvr.ccz'},
            {0,'oasis_27.pvr.ccz'},
            {0,'oasis_28.pvr.ccz'},
            {0,'oasis_29.pvr.ccz'},
            {0,'oasis_30.pvr.ccz'},
            {0,'oasis_31.pvr.ccz'},
            {0,'oasis_32.pvr.ccz'},
            {0,'oasis_33.pvr.ccz'},
            {0,'oasis_34.pvr.ccz'},
            {0,'oasis_35.pvr.ccz'},
            {0,'oasis_36.pvr.ccz'},
            {0,'oasis_37.pvr.ccz'},
            {0,'oasis_38.pvr.ccz'},

            {0,'ch5_01.pvr.ccz'},
            {0,'ch5_02.pvr.ccz'},
            {0,'ch5_03.pvr.ccz'},
            {0,'ch5_04.pvr.ccz'},
            {0,'ch5_05.pvr.ccz'},
            {0,'ch5_06.pvr.ccz'},
            {0,'ch5_07.pvr.ccz'},
            {0,'ch5_08.pvr.ccz'},
            {0,'ch5_09.pvr.ccz'},
            {0,'ch5_10.pvr.ccz'},
            {0,'ch5_11.pvr.ccz'},
            {0,'ch5_12.pvr.ccz'},
            {0,'ch5_13.pvr.ccz'},
            {0,'ch5_14.pvr.ccz'},
            {0,'ch5_15.pvr.ccz'},
            {0,'ch5_16.pvr.ccz'},
            {0,'ch5_17.pvr.ccz'},
            {0,'ch5_18.pvr.ccz'},
            {0,'ch5_19.pvr.ccz'},
            {0,'ch5_20.pvr.ccz'},
            {0,'ch5_21.pvr.ccz'},
            {0,'ch5_22.pvr.ccz'},
            {0,'ch5_23.pvr.ccz'},
            {0,'ch5_24.pvr.ccz'},
            {0,'ch5_25.pvr.ccz'},
            {0,'ch5_26.pvr.ccz'},
            {0,'ch5_27.pvr.ccz'},
            {0,'ch5_28.pvr.ccz'},
            {0,'ch5_29.pvr.ccz'},
            {0,'ch5_30.pvr.ccz'},
            {0,'ch5_31.pvr.ccz'},
            {0,'ch5_32.pvr.ccz'},
            {0,'ch5_33.pvr.ccz'},
            {0,'ch5_34.pvr.ccz'},
            {0,'ch5_35.pvr.ccz'},
            {0,'ch5_36.pvr.ccz'},
            {0,'ch5_37.pvr.ccz'},

            {0,'comingSoon.pvr.ccz'},


            {0,'ch5_38.pvr.ccz'},
            {0,'ch5_39.pvr.ccz'},
            {0,'ch5_40.pvr.ccz'},
            {0,'ch5_41.pvr.ccz'},
            {0,'ch5_42.pvr.ccz'},

            {0,'ch6_01.pvr.ccz'},
            {0,'ch6_02.pvr.ccz'},
            {0,'ch6_03.pvr.ccz'},
            {0,'ch6_04.pvr.ccz'},
            {0,'ch6_05.pvr.ccz'},
            {0,'ch6_06.pvr.ccz'},
            {0,'ch6_07.pvr.ccz'},
            {0,'ch6_08.pvr.ccz'},
            {0,'ch6_09.pvr.ccz'},
            {0,'ch6_10.pvr.ccz'},
            {0,'ch6_11.pvr.ccz'},
            {0,'ch6_12.pvr.ccz'},
            {0,'ch6_13.pvr.ccz'},
            {0,'ch6_14.pvr.ccz'},

            {0,'ch6E_01.pvr.ccz'},
            {0,'ch6E_02.pvr.ccz'},
            {0,'ch6E_03.pvr.ccz'},

            {0,'ch6_15.pvr.ccz'},
            {0,'ch6_16.pvr.ccz'},
            {0,'ch6_17.pvr.ccz'},
            {0,'ch6_18.pvr.ccz'},
            {0,'ch6_19.pvr.ccz'},

            {0,'ch7_01.pvr.ccz'},
            {0,'ch7_02.pvr.ccz'},
            {0,'ch7_03.pvr.ccz'},
            {0,'ch7_04.pvr.ccz'},

            {0,'ch7_e1.pvr.ccz'},
            {0,'ch7_e2.pvr.ccz'},
            {0,'ch7_e3.pvr.ccz'},
            {0,'ch7_e4.pvr.ccz'},
            {0,'ch7_e5.pvr.ccz'},

            {0,'ch7_05.pvr.ccz'},
            {0,'ch7_06.pvr.ccz'},
            {0,'ch7_07.pvr.ccz'},
            {0,'ch7_08.pvr.ccz'},
            {0,'ch7_09.pvr.ccz'},
            {0,'ch7_10.pvr.ccz'},
            {0,'ch7_11.pvr.ccz'},
            {0,'ch7_12.pvr.ccz'},
            {0,'ch7_13.pvr.ccz'},
            {0,'ch7_14.pvr.ccz'},
            {0,'ch7_15.pvr.ccz'},
            {0,'ch7_16.pvr.ccz'},
            {0,'ch7_17.pvr.ccz'},
            {0,'ch7_18.pvr.ccz'},
            {0,'ch7_19.pvr.ccz'},
            {0,'ch7_20.pvr.ccz'},
            {0,'ch7_21.pvr.ccz'},
            {0,'ch7_22.pvr.ccz'},
            {0,'ch7_23.pvr.ccz'},
            {0,'ch7_24.pvr.ccz'},
            {0,'ch7_25.pvr.ccz'},
            {0,'ch7_26.pvr.ccz'},
            {0,'ch7_27.pvr.ccz'},

            {0,'ch8_01.pvr.ccz'},
            {0,'ch8_02.pvr.ccz'},
            {0,'ch8_03.pvr.ccz'},
            {0,'ch8_04.pvr.ccz'},
            {0,'ch8_05.pvr.ccz'},
            {0,'ch8_06.pvr.ccz'},
            {0,'ch8_07.pvr.ccz'},
            {0,'ch8_08.pvr.ccz'},
            {0,'ch8_09.pvr.ccz'},
            {0,'ch8_10.pvr.ccz'},
            {0,'ch8_11.pvr.ccz'},
            {0,'ch8_12.pvr.ccz'},
            {0,'ch8_13.pvr.ccz'},
            {0,'ch8_14.pvr.ccz'},
            {0,'ch8_15.pvr.ccz'},
            {0,'ch8_16.pvr.ccz'},
            {0,'ch8_17.pvr.ccz'},
            {0,'ch8_18.pvr.ccz'},
            {0,'ch8_19.pvr.ccz'},
            {0,'ch8_20.pvr.ccz'},
            {0,'ch8_21.pvr.ccz'},
            {0,'ch8_22.pvr.ccz'},
            {0,'ch8_23.pvr.ccz'},
         },
         ['keep'] = {
             {1, 'shop.plist', 'shop.pvr'},
             -- 通用音效,不卸载
             {3,"ui_show_panel"},
             {3,"ui_close_panel"},
             {3,"ui_show_target"},
             {3,"ui_hide_target"},
             {3,"ui_exit"},
             {3,"ui_buy"},
             {3,"common_click"},
             {3,"common_menu"},
             {3,"refueling_bird"},
         },
    },

   ['app.battlescene.BattleScene'] = {
       ['loadRGBA8888']={
            {2,'effect/pigtower/eagle/eagle.json','effect/pigtower/eagle/eagle.atlas', "effect/pigtower/eagle/eagle.png"},
            {2,'effect/pigtower/leaf.json','effect/pigtower/leaf.atlas', "effect/pigtower/leaf.png"},
            {2,"effect/pigtower/butterfly/butterfly(loop).json" ,"effect/pigtower/butterfly/butterfly(loop).atlas" ,"effect/pigtower/butterfly/butterfly(loop).png"},

       },
        ['load'] = {
            {1, 'gfx/terrain.plist', 'gfx/terrain.pvr'},
            {1, 'in_game_else.plist', 'in_game_else.pvr'},
            {1, 'color_streamer.plist', 'color_streamer.png'},
            {1, 'bonusStream.plist', 'bonusStream.png'},
            {1, 'tower_ui.plist', 'tower_ui.pvr'},
            --动画
            {2,'effect/bg1/forest.json','effect/bg1/forest.atlas', "effect/bg1/forest.png"},
            {2,'effect/bg2/beach.json','effect/bg2/beach.atlas', "effect/bg2/beach.png"},
            {2,'effect/bg3/desert.json','effect/bg3/desert.atlas', "effect/bg3/desert.png"},
            {2,'effect/bg4/moor.json','effect/bg4/moor.atlas', "effect/bg4/moor.png"},
            {2,'effect/bg5/pigcity.json','effect/bg5/pigcity.atlas', "effect/bg5/pigcity.png"},
            {2,'effect/bg6/garden.json','effect/bg6/garden.atlas', "effect/bg6/garden.png"},
            {2,'effect/bg7/snow.json','effect/bg7/snow.atlas', "effect/bg7/snow.png"},
            {2,'effect/bg8/space.json','effect/bg8/space.atlas', "effect/bg8/space.png"},
            -- 成功或失败资源
            {2,'effect/ui_win/blue.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/guang.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/red.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/skeleton.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/star_1.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/star_2.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/star_3.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/star1.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/star2.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/star3.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2,'effect/ui_win/yellow.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},

            {2,'effect/failed/balloons.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2,'effect/failed/dailypig.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2,'effect/failed/heart.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2,'effect/failed/pig1.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2,'effect/failed/pig2.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2,'effect/failed/pig3.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2,'effect/failed/succeed.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            -- 音效
            {3,"target_complete"},
            {3,"target_reached"},
            {3,"booster_combination"},
            {3,"rocket"},
            {3,"rocket_rocket"},
            {3,"rocket_bomb"},
            {3,"bomb_bomb"},
            {3,"bomb"},
            {3,"laser_gun_laser_gun"},
            {3,"laser_gun"},
            {3,"slingshot"},
            {3,"twister"},
            {3,"pigs_cheer"},
            {3,"get_star_1"},
            {3,"get_star_2"},
            {3,"get_star_3"},
            {3,"clear_eliminate_wow"},
            {3,"clear_eliminate_eggscellent"},
            {3,"clear_eliminate_blasty"},
            {3,"plus_5_moves_fly"},
            {3,"plus_5_moves"},
            {3,"outofmoves_loop"},
            --{3,"levelfinish_screen"},
            {3,"levelfailed_stinger"},
            {3,"levelfail_balloonpop"},
        },
        ['extraUnload'] = {
            {0,"bg/battle_continue_bg_01.png"},
            {0,"bg/battle_continue_bg_02.png"},
            {0,"bg/battle_continue_bg_03.png"},
            {0,"bg/battle_continue_bg_04.png"},
            {0,"bg/begin_01.png"},
            {0,"bg/begin_02.png"},
            {0,"bg/begin_03.png"},
            {0,"bg/begin_04.png"},
            {0,"bg/dailyImg_01.png"},
            {0,"bg/dailyImg_02.png"},
            {0,"bg/dailyImg_03.png"},
            {0,"bg/dailyImg_04.png"},
            {0,"bg/frame_max_01.png"},
            {0,"bg/frame_max_02.png"},
            {0,"bg/frame_max_03_01.png"},
            {0,"bg/frame_max_03_02.png"},
            {0,"bg/frame_max_03_03.png"},
            {0,"bg/frame_max_03_04.png"},
            {0,"bg/frame_max_03.png"},
            {0,"bg/frame_max_04.png"},
            {0,"bg/frame_median_01.png"},
            {0,"bg/frame_median_02.png"},
            {0,"bg/frame_median_03.png"},
            {0,"bg/frame_median_04.png"},
            {0,"bg/heart_purchase_bg_01.png"},
            {0,"bg/heart_purchase_bg_02.png"},
            {0,"bg/heart_purchase_bg_03.png"},
            {0,"bg/heart_purchase_bg_04.png"},
            {0,"bg/newBg_large_01.png"},
            {0,"bg/newBg_large_02.png"},
            {0,"bg/newBg_large_03.png"},
            {0,"bg/newBg_large_04.png"},
            {0,"bg/newBg_normal_01.png"},
            {0,"bg/newBg_normal_02.png"},
            {0,"bg/newBg_normal_03.png"},
            {0,"bg/newBg_normal_04.png"},
            {0, 'back3.png'},
            {0, 'back4.png'},
            {0, 'circle_mask.png'},
            {0, 'guide_1.png'},
            {0, 'guide_3.png'},
            {0, 'guide_4.png'},
            {0, 'target_mask.png'},
            {0, 'guide_tip_bomb.png'},
            {0, 'guide_tip_gun.png'},
            {0, 'guide_tip_rocket.png'},

            {0, 'gfx/tail.png'},

            {0, 'gfx/tail_x.png'},
            {0, 'gfx/tail_head.png'},
            {0, 'gfx/tail_head_1.png'},
            {0, 'gfx/tail_head_2.png'},
            {0, 'gfx/tp_yellow.png'},
            {0, 'gfx/tp_red.png'},
            {0, 'gfx/tp_black.png'},
            {0, 'gfx/tp_blue.png'},
            {0, 'gfx/tp_green.png'},
            {0, 'gfx/tp_orange.png'},
            {0, 'gfx/tp_pink.png'},
            {0, 'gfx/tp_white.png'},

            {0,"gfx/back2.png"},
            {0,"gfx/back.png"},
            {0,"gfx/blood1.png"},
            {0,"gfx/blood2.png"},
            {0,"gfx/bubble_2.png"},
            {0,"gfx/bubble_4.png"},
            {0,"gfx/bubble_5.png"},
            {0,"gfx/bubble_6.png"},
            {0,"gfx/bubble_7.png"},
            {0,"gfx/light.png"},
            {0,"gfx/progress_bar.png"},
            {0,"gfx/stepNumber2.png"},
            {0,"gfx/stepNumber.png"},
            {0,"gfx/bubble_3.png"},
            {0,"gfx/meteor_1.png"},
            {0,"gfx/bubble_1.png"},
            {0,"gfx/meteor_2.png"},
            {0,"gfx/nail.png"},
            {0,"gfx/progress_bar2.png"},

            {0, 'gfx/game/bg_1.png'},
            {0, 'gfx/game/bg_2.png'},
            {0, 'gfx/game/bg_3.png'},
            {0, 'gfx/game/bg_4.png'},
            {0, 'gfx/game/bg_5.png'},
            {0, 'gfx/guide/guide_tip_bomb.png'},
            {0, 'gfx/guide/guide_tip_gun.png'},
            {0, 'gfx/guide/guide_tip_rocket.png'},
            {0, 'gfx/feathers/f_1.png'},
            {0, 'gfx/feathers/f_2.png'},
            {0, 'gfx/feathers/f_3.png'},
            {0, 'gfx/feathers/f_4.png'},
            {0, 'gfx/feathers/f_5.png'},
            {0, 'gfx/feathers/f_6.png'},
            {0, 'gfx/feathers/f_7.png'},
            {1, 'FriendsBox.plist', 'FriendsBox.pvr'},

           --  不常用元素卸载
            {2,"effect/pigtower/butterfly/butterfly(loop).json" ,"effect/pigtower/butterfly/butterfly(loop).atlas" ,"effect/pigtower/butterfly/butterfly(loop).png"},
            {2,'effect/pigtower/eagle/eagle.json','effect/pigtower/eagle/eagle.atlas', "effect/pigtower/eagle/eagle.png"},
            {2,'effect/bg1/forest.json','effect/bg1/forest.atlas', "effect/bg1/forest.png"},
            {2,'effect/bg2/beach.json','effect/bg2/beach.atlas', "effect/bg2/beach.png"},
            {2,'effect/bg3/desert.json','effect/bg3/desert.atlas', "effect/bg3/desert.png"},
            {2,'effect/bg4/moor.json','effect/bg4/moor.atlas', "effect/bg4/moor.png"},
            {2,'effect/bg5/pigcity.json','effect/bg5/pigcity.atlas', "effect/bg5/pigcity.png"},
            {2,'effect/bg6/garden.json','effect/bg6/garden.atlas', "effect/bg6/garden.png"},
            {2,'effect/bg7/snow.json','effect/bg7/snow.atlas', "effect/bg7/snow.png"},
            {2,'effect/bg8/space.json','effect/bg8/space.atlas', "effect/bg8/space.png"},
            {2,'effect/pigtower/leaf.json','effect/pigtower/leaf.atlas', "effect/pigtower/leaf.png"},
            {2, "effect/ball/skeleton.json", "effect/ball/skeleton.atlas", "effect/ball/skeleton.png"},
            {2, "effect/balloon/skeleton.json", "effect/balloon/skeleton.atlas", "effect/balloon/skeleton.png"},
            {2, "effect/belt/gear/skeleton.json", "effect/belt/gear/skeleton.atlas", "effect/belt/gear/skeleton.png"},
            {2, "effect/belt/lightning/shandian.json", "effect/belt/lightning/shandian.atlas", "effect/belt/lightning/shandian.png"},
            {2, "effect/big_pig/skeleton.json", "effect/big_pig/final.atlas", "effect/big_pig/final.pvr.ccz"},
            {2, "effect/biscuit/blackbaby.json", "effect/biscuit/blackbaby.atlas", "effect/biscuit/blackbaby.png"},
            {2, "effect/biscuit/bluebaby.json", "effect/biscuit/bluebaby.atlas", "effect/biscuit/bluebaby.png"},
            {2, "effect/biscuit/nest1.json", "effect/biscuit/nest1.atlas", "effect/biscuit/nest1.png"},
            {2, "effect/biscuit/nest2.json", "effect/biscuit/nest2.atlas", "effect/biscuit/nest2.png"},
            {2, "effect/biscuit/orangebaby.json", "effect/biscuit/orangebaby.atlas", "effect/biscuit/orangebaby.png"},
            {2, "effect/biscuit/redbaby.json", "effect/biscuit/redbaby.atlas", "effect/biscuit/redbaby.png"},
            {2, "effect/biscuit/whitebaby.json", "effect/biscuit/whitebaby.atlas", "effect/biscuit/whitebaby.png"},
            {2, "effect/biscuit/yellowbaby.json", "effect/biscuit/yellowbaby.atlas", "effect/biscuit/yellowbaby.png"},
            {2, "effect/bomb_bucket/bomb/skeleton.json", "effect/bomb_bucket/bomb/skeleton.atlas", "effect/bomb_bucket/bomb/skeleton.png"},
            {2, "effect/bomb_bucket/bucket/skeleton.json", "effect/bomb_bucket/bucket/skeleton.atlas", "effect/bomb_bucket/bucket/skeleton.png"},
            {2, "effect/bomb_bucket/bucket/skeleton_bottle.json", "effect/bomb_bucket/bucket/skeleton_bottle.atlas", "effect/bomb_bucket/bucket/skeleton_bottle.png"},
            {2, "effect/box/mysterious_box.json", "effect/box/mysterious_box.atlas", "effect/box/mysterious_box.png"},
            {2, 'effect/bread/skeleton_breadcover.json','effect/bread/final.atlas', "effect/bread/final.pvr.ccz"},
            {2, 'effect/bread/skeleton_breadG.json','effect/bread/final.atlas', "effect/bread/final.pvr.ccz"},
            {2, 'effect/bread/skeleton_breadYa.json','effect/bread/final.atlas', "effect/bread/final.pvr.ccz"},
            {2, 'effect/bread/skeleton_eatbreadfall.json','effect/bread/final.atlas', "effect/bread/final.pvr.ccz"},
            {2, 'effect/brick/ice/skeleton.json','effect/brick/ice/skeleton.atlas', "effect/brick/ice/skeleton.png"},
            {2, 'effect/brick/ice/14/skeleton.json','effect/brick/ice/14/skeleton.atlas', "effect/brick/ice/14/skeleton.png"},
            {2, 'effect/brick/ice/15/skeleton.json','effect/brick/ice/15/skeleton.atlas', "effect/brick/ice/15/skeleton.png"},
            {2, 'effect/brick/ice/16/skeleton.json','effect/brick/ice/16/skeleton.atlas', "effect/brick/ice/16/skeleton.png"},
            {2, 'effect/brick/stone/skeleton.json','effect/brick/stone/skeleton.atlas', "effect/brick/stone/skeleton.png"},
            {2, 'effect/brick/stone/14/skeleton.json','effect/brick/stone/14/skeleton.atlas', "effect/brick/stone/14/skeleton.png"},
            {2, 'effect/brick/stone/15/skeleton.json','effect/brick/stone/15/skeleton.atlas', "effect/brick/stone/15/skeleton.png"},
            {2, 'effect/brick/stone/16/skeleton.json','effect/brick/stone/16/skeleton.atlas', "effect/brick/stone/16/skeleton.png"},
            {2, 'effect/brick/wood/skeleton.json','effect/brick/wood/skeleton.atlas', "effect/brick/wood/skeleton.png"},
            {2, 'effect/brick/wood/14/skeleton.json','effect/brick/wood/14/skeleton.atlas', "effect/brick/wood/14/skeleton.png"},
            {2, 'effect/brick/wood/15/skeleton.json','effect/brick/wood/15/skeleton.atlas', "effect/brick/wood/15/skeleton.png"},
            {2, 'effect/brick/wood/16/skeleton.json','effect/brick/wood/16/skeleton.atlas', "effect/brick/wood/16/skeleton.png"},
            {2, "effect/cloud/cloud.json", "effect/cloud/cloud.atlas", "effect/cloud/cloud.png"},
            {2, "effect/collect_port/skeleton.json", "effect/collect_port/skeleton.atlas", "effect/collect_port/skeleton.png"},
            {2, "effect/color_bucket/skeleton.json", "effect/color_bucket/final.atlas", "effect/color_bucket/final.pvr.ccz"},
            {2, "effect/color_bucket/umbrella.json", "effect/color_bucket/final.atlas", "effect/color_bucket/final.pvr.ccz"},
            {2, "effect/color_bucket/bucket_hit.json", "effect/color_bucket/final.atlas", "effect/color_bucket/final.pvr.ccz"},
            {2, "effect/deadlock/skeleton.json", "effect/deadlock/skeleton.atlas", "effect/deadlock/skeleton.png"},
            {2, "effect/deadlock/twister/skeleton.json", "effect/deadlock/twister/skeleton.atlas", "effect/deadlock/twister/skeleton.png"},
            {2, "effect/egg/skeleton.json", "effect/egg/skeleton.atlas", "effect/egg/skeleton.png"},

            {2, 'effect/failed/pig1.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2, 'effect/failed/pig2.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2, 'effect/failed/pig3.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2, 'effect/failed/heart.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2, 'effect/failed/balloons.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2, 'effect/failed/succeed.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},
            {2, 'effect/failed/dailypig.json','effect/failed/final.atlas', "effect/failed/final.pvr.ccz"},

            {2, "effect/flip_board/light.json", "effect/flip_board/light.atlas", "effect/flip_board/light.png"},
            {2, "effect/flip_board/plank.json", "effect/flip_board/plank.atlas", "effect/flip_board/plank.png"},
            {2, "effect/flip_board/skeleton.json", "effect/flip_board/skeleton.atlas", "effect/flip_board/skeleton.png"},
            {2, "effect/guideBird/skeleton.json", "effect/guideBird/skeleton.atlas", "effect/guideBird/skeleton.png"},
            {2, "effect/hairball/ufo1/skeleton.json", "effect/hairball/ufo1/skeleton.atlas", "effect/hairball/ufo1/skeleton.png"},
            {2, "effect/hairball/ufo2/skeleton.json", "effect/hairball/ufo1/skeleton.atlas", "effect/hairball/ufo1/skeleton.png"},
            {2, "effect/lock/1.json", "effect/lock/final.atlas", "effect/lock/final.pvr.ccz"},
            {2, "effect/lock/2.json", "effect/lock/final.atlas", "effect/lock/final.pvr.ccz"},
            {2, "effect/magic_pig/cloud.json", "effect/magic_pig/cloud.atlas", "effect/magic_pig/cloud.png"},
            {2, "effect/magic_pig/pig.json", "effect/magic_pig/pig.atlas", "effect/magic_pig/pig.png"},
            {2, "effect/magic_pig/quan.json", "effect/magic_pig/quan.atlas", "effect/magic_pig/quan.png"},
            {2, "effect/magic_pig/yan.json", "effect/magic_pig/yan.atlas", "effect/magic_pig/yan.png"},
            {2, "effect/pig/skeleton.json", "effect/pig/final.atlas", "effect/pig/final.pvr.ccz"},
            {2, "effect/score/eggscelent.json", "effect/score/eggscelent.atlas", "effect/score/eggscelent.png"},
            {2, "effect/score/red.json", "effect/score/red.atlas", "effect/score/red.png"},
            {2, "effect/score/skeleton.json", "effect/score/skeleton.atlas", "effect/score/skeleton.png"},
            {2, "effect/target_complete/skeleton.json", "effect/target_complete/skeleton.atlas", "effect/target_complete/skeleton.png"},

            {2, 'effect/ui_win/blue.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/guang.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/red.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/skeleton.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/star_1.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/star_2.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/star_3.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/star1.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/star2.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/star3.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            {2, 'effect/ui_win/yellow.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},
            -- {2, 'effect/ui_win/dailypig.json','effect/ui_win/final.atlas', "effect/ui_win/final.pvr.ccz"},

            {2, 'effect/windmill/balloons/skeleton_balloons.json','effect/windmill/balloons/skeleton_balloons.atlas', "effect/windmill/balloons/skeleton_balloons.png"},
            {2, 'effect/windmill/wood/skeleton_chips.json','effect/windmill/wood/skeleton_chips.atlas', "effect/windmill/wood/skeleton_chips.png"},

            -- tail全卸载
            {2, "effect/tail/five.json","effect/tail/final.atlas","effect/tail/final.pvr.ccz"},
            {2, "effect/tail/addfive_bomb.json","effect/tail/final.atlas","effect/tail/final.pvr.ccz"},
            {2, "effect/tail/skeleton_bomb.json","effect/tail/final.atlas","effect/tail/final.pvr.ccz"},
            {2, "effect/tail/skeleton_star.json","effect/tail/final.atlas","effect/tail/final.pvr.ccz"},
            {2, "effect/tail/three.json","effect/tail/final.atlas","effect/tail/final.pvr.ccz"},

            -- bird全卸载
            {2, 'effect/birdfly/skeleton_black.json',"effect/birdfly/skeleton_black.atlas", "effect/birdfly/skeleton_black.png"},
            {2, 'effect/birdfly/skeleton_blue.json',"effect/birdfly/skeleton_blue.atlas", "effect/birdfly/skeleton_blue.png"},
            {2, 'effect/birdfly/skeleton_orange.json',"effect/birdfly/skeleton_orange.atlas", "effect/birdfly/skeleton_orange.png"},
            {2, 'effect/birdfly/skeleton_red.json',"effect/birdfly/skeleton_red.atlas", "effect/birdfly/skeleton_red.png"},
            {2, 'effect/birdfly/skeleton_wave.json',"effect/birdfly/skeleton_wave.atlas", "effect/birdfly/skeleton_wave.png"},
            {2, 'effect/birdfly/skeleton_white.json',"effect/birdfly/skeleton_white.atlas", "effect/birdfly/skeleton_white.png"},
            {2, 'effect/birdfly/skeleton_yellow.json',"effect/birdfly/skeleton_yellow.atlas", "effect/birdfly/skeleton_yellow.png"},

            {2, "effect/shadow/black/skeleton.json", "effect/shadow/black/final.atlas", "effect/shadow/final.pvr.ccz"},
            {2, "effect/shadow/blue/skeleton.json", "effect/shadow/blue/final.atlas", "effect/shadow/final.pvr.ccz"},
            {2, "effect/shadow/green/skeleton.json", "effect/shadow/green/final.atlas", "effect/shadowfinal.pvr.ccz"},
            {2, "effect/shadow/orange/skeleton.json", "effect/shadow/orange/final.atlas", "effect/shadow/final.pvr.ccz"},
            {2, "effect/shadow/red/skeleton.json", "effect/shadow/red/final.atlas", "effect/shadow/final.pvr.ccz"},
            {2, "effect/shadow/white/skeleton.json", "effect/shadow/white/final.atlas", "effect/shadow/final.pvr.ccz"},
            {2, "effect/shadow/yellow/skeleton.json", "effect/shadow/yellow/final.atlas", "effect/shadow/final.pvr.ccz"},

            -- block
            {2, "effect/block/skeleton.json","effect/block/skeleton.atlas","effect/block/skeleton.png"},
            {2, "effect/target_shine/skeleton.json","effect/target_shine/skeleton.atlas","effect/target_shine/skeleton.png"},

            -- target
            {2, "effect/target_block/skeleton_black.json", "effect/target_block/skeleton_black.atlas", "effect/target_block/skeleton_black.png"},
            {2, "effect/target_block/skeleton_blue.json", "effect/target_block/skeleton_blue.atlas", "effect/target_block/skeleton_blue.png"},
            {2, "effect/target_block/skeleton_orange.json", "effect/target_block/skeleton_orange.atlas", "effect/target_block/skeleton_orange.png"},
            {2, "effect/target_block/skeleton_pig.json", "effect/target_block/skeleton_pig.atlas", "effect/target_block/skeleton_pig.png"},
            {2, "effect/target_block/skeleton_red.json", "effect/target_block/skeleton_red.atlas", "effect/target_block/skeleton_red.png"},
            {2, "effect/target_block/skeleton_wave.json", "effect/target_block/skeleton_wave.atlas", "effect/target_block/skeleton_wave.png"},
            {2, "effect/target_block/skeleton_white.json", "effect/target_block/skeleton_white.atlas", "effect/target_block/skeleton_white.png"},
            {2, "effect/target_block/skeleton_yellow.json", "effect/target_block/skeleton_yellow.atlas", "effect/target_block/skeleton_yellow.png"},
            {2, "effect/target_block/skeleton.json", "effect/target_block/skeleton.atlas", "effect/target_block/skeleton.png"},

            {2, "effect/target_block/box/skeleton.json", "effect/target_block/box/skeleton.atlas", "effect/target_block/box/skeleton.png"},
            {2, "effect/target_block/bubble/skeleton.json", "effect/target_block/bubble/skeleton.atlas", "effect/target_block/bubble/skeleton.png"},
            {2, "effect/target_block/cloud/skeleton.json", "effect/target_block/cloud/skeleton.atlas", "effect/target_block/cloud/skeleton.png"},
            {2, "effect/target_block/egg/skeleton.json", "effect/target_block/egg/skeleton.atlas", "effect/target_block/egg/skeleton.png"},
            {2, "effect/target_block/helium balloons/skeleton.json", "effect/target_block/helium balloons/skeleton.atlas", "effect/target_block/helium balloons/skeleton.png"},
            {2, "effect/target_block/stone/skeleton.json", "effect/target_block/stone/skeleton.atlas", "effect/target_block/stone/skeleton.png"},

            {2, "effect/target_biscuit/blackbaby.json", "effect/target_biscuit/blackbaby.atlas", "effect/target_biscuit/blackbaby.png"},
            {2, "effect/target_biscuit/bluebaby.json", "effect/target_biscuit/bluebaby.atlas", "effect/target_biscuit/bluebaby.png"},
            {2, "effect/target_biscuit/orangebaby.json", "effect/target_biscuit/orangebaby.atlas", "effect/target_biscuit/orangebaby.png"},
            {2, "effect/target_biscuit/redbaby.json", "effect/target_biscuit/redbaby.atlas", "effect/target_biscuit/redbaby.png"},
            {2, "effect/target_biscuit/whitebaby.json", "effect/target_biscuit/whitebaby.atlas", "effect/target_biscuit/whitebaby.png"},
            {2, "effect/target_biscuit/yellowbaby.json", "effect/target_biscuit/yellowbaby.atlas", "effect/target_biscuit/yellowbaby.png"},

            -- hand
            {2, "effect/hand/skeleton.json","effect/hand/skeleton.atlas","effect/hand/skeleton.png"},
            -- item buy bg
            {2, "effect/itembg_light/skeleton.json","effect/itembg_light/skeleton.atlas","effect/itembg_light/skeleton.png"},
            -- add step
            {2, "effect/add_step/black/red.json","effect/add_step/black/red.atlas","effect/add_step/black/red.png"},
            {2, "effect/add_step/blue/red.json","effect/add_step/blue/red.atlas","effect/add_step/blue/red.png"},
            {2, "effect/add_step/red/red.json","effect/add_step/red/red.atlas","effect/add_step/red/red.png"},
            {2, "effect/add_step/white/red.json","effect/add_step/white/red.atlas","effect/add_step/white/red.png"},
            {2, "effect/add_step/yellow/red.json","effect/add_step/yellow/red.atlas","effect/add_step/yellow/red.png"},
            -- zhoufx
            {2, "effect/zhuofx/zhuofx.json","effect/zhuofx/zhuofx.atlas","effect/zhuofx/zhuofx.png"},
            -- skull
            {2, "effect/skull/skull.json","effect/skull/skull.atlas","effect/skull/skull.png"},
            {2, "effect/skull/line.json","effect/skull/line.atlas","effect/skull/line.png"},
            -- die_smoke
            {2, "effect/die_smoke/diesmoke.json", "effect/die_smoke/diesmoke.atlas", "effect/die_smoke/diesmoke.png"},
            -- export
            {2, "effect/export/balloon.json", "effect/export/balloon.atlas", "effect/export/balloon.png"},
            {2, "effect/export/red.json", "effect/export/red.atlas", "effect/export/red.png"},
            -- inflactor
            {2, "effect/inflactor/skeleton.json", "effect/inflactor/skeleton.atlas", "effect/inflactor/skeleton.png"},
            -- exit_level_heart
            {2, "effect/exit_level_heart/skeleton.json", "effect/exit_level_heart/skeleton.atlas", "effect/exit_level_heart/skeleton.png"},
            -- bonus_time
            {2, "effect/bonus_time/skeleton.json", "effect/bonus_time/skeleton.atlas", "effect/bonus_time/skeleton.png"},
        },
        ['keep'] = {
        },
   },
}

return resources
